# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Calendar_Alice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CalculateCalendarLogic'

  target 'Calendar_AliceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Calendar_AliceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
